---
# tasks file for cobalt_strike
- name: Grab Cobalt Strike tarball from S3
  local_action:
    module: aws_s3
    bucket: cobalt-strike-for-pca-teamservers
    object: cobaltstrike.tgz
    dest: /tmp/cobaltstrike.tgz
    mode: get
  become: no

- name: Copy the Cobalt Strike tarball
  copy:
    src: /tmp/cobaltstrike.tgz
    dest: /tmp/cobaltstrike.tgz
    owner: root
    group: root
    mode: 0644

- name: Extract the Cobalt Strike tarball
  unarchive:
    src: /tmp/cobaltstrike.tgz
    dest: /opt
    owner: root
    group: root
    remote_src: yes

- name: Delete remote copy of Cobalt Strike tarball
  file:
    path: /tmp/cobaltstrike.tgz
    state: absent

- name: Delete local copy of Cobalt Strike tarball
  local_action:
    module: file
    path: /tmp/cobaltstrike.tgz
    state: absent
  become: no
