---
- hosts: all
  name: >
    Add banner, add htop, add NVMe support, and make journald logs
    persistent
  become: yes
  become_method: sudo
  roles:
    - banner
    - htop
    - nvme
    - persist_journald

- hosts: all
  name: Install Cobalt Strike and server-setup script
  become: yes
  become_method: sudo
  roles:
    # Cobalt Strike requires that Java be installed, so OpenJDK must
    # go first.
    - openjdk
    - role: cobalt_strike
      vars:
        # Use the bucket in the old CyHy account
        bucket_name: cobalt-strike-for-pca-teamservers
    - role: server_setup
      vars:
        # Use the PCA-specific version of the ServerSetup script
        use_pca_script: true
  tasks:
    - name: Install dnsutils
      package:
        name: dnsutils
