---
- hosts: all
  name: Update the base image and install python
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python

# - hosts: nmap
#   name: Install nmap
#   become: yes
#   become_method: sudo
#   roles:
#     - nmap
