# Install terraform, packer, and ansible
before_install:
  - wget https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - wget https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip -O packer.zip
  - sudo unzip packer.zip -d /opt/packer
  - sudo ln -s /opt/packer/packer /usr/bin/packer
  - rm -f packer.zip
  - sudo apt-get install ansible

# We don't initialize the Terraform backend because Travis doesn't
# have credentials to connect to our AWS S3 bucket where the Terraform
# state is stored.
#
# We don't check Terraform variables because we don't have a tfvars
# file to use.
script:
  - packer validate packer/teamserver.json
  - cd terraform
  - terraform init -backend=false .
  - terraform validate .
  - cd ..
