---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

# Install terraform, packer, and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - >
    wget
    https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip
    -O packer.zip
  - sudo unzip packer.zip -d /opt/packer
  - sudo ln -s /opt/packer/packer /usr/bin/packer
  - rm -f packer.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt
script:
  - pre-commit run --all-files
