---
# tasks file for cobaltstrike

#
# License Cobalt Strike
#
- name: Grab the Cobalt Strike license from S3
  local_action:
    module: aws_s3
    bucket: cobalt-strike-for-pca-teamservers
    object: cobaltstrike.license
    dest: /tmp/cobaltstrike.license
    mode: get
  become: no

- name: Copy Cobalt Strike license
  copy:
    src: /tmp/cobaltstrike.license
    dest: /root/.cobaltstrike.license
    mode: 0400

- name: Delete local copy of Cobalt Strike license
  local_action:
    module: file
    path: /tmp/cobaltstrike.license
    state: absent
  become: no


#
# Upgrade Cobalt Strike
#
# The expect Ansible module requires pexpect
#
- name: Install pexpect
  package:
    name:
      - python-pexpect
 
- name: Upgrade Cobalt Strike
  expect:
    chdir: /opt/cobaltstrike
    command: sh ./update
    timeout: 300
    responses:
      continue: "yes"
  async: 300
  poll: 30
